package com.jm.hrhelper.greendao.dao;

import com.jm.hrhelper.greendao.entity.Staff;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 *  Created by mingtingjie on 18/4/23.
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig salaryDaoConfig;

    private final SalaryDao salaryDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        salaryDaoConfig = daoConfigMap.get(SalaryDao.class).clone();
        salaryDaoConfig.initIdentityScope(type);

        salaryDao = new SalaryDao(salaryDaoConfig, this);

        registerDao(Staff.class, salaryDao);
    }
    
    public void clear() {
        salaryDaoConfig.clearIdentityScope();
    }

    public SalaryDao getSalaryDao() {
        return salaryDao;
    }

}
